### ISSUE TITLE
new permissions for rds

### ISSUE THREAD

**Issue by davgibney1** [widdix/complete-aws-iam-reference#11]
rds:StartDbInstance
rds:StopDbInstance

**Comment by michaelwittig** [comment]
I opened a Support Ticket to clarify the resource level permissions and conditions. It's not yet documented http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAM.ResourcePermissions.html

**Comment by michaelwittig** [comment]
"adding resource-level constraints is currently not available for the listed API actions"
