### ISSUE TITLE
iam:ListAccessKeys

### ISSUE THREAD

**Issue by b2bking** [widdix/complete-aws-iam-reference#15]
Please make sure to provide all the fields and describe your issue.

* Service: IAM
* Action: list all access keys

Please describe your issue here!

## Example
After I create a new access key for the user, I want to find it in a list by invoking list_access_keys.
However, the newly created access key does not appear in the list. Only after I use some services it appears in the list.

* Service: IAM
* Action: Create new access key

Does it automatically appear in the list that is retrieved by invoking list_access_keys function or method?

**Comment by michaelwittig** [comment]
the questions seems to be off-topic. this project is abut iam policies and not about why or why not the list access keys action retrieves the list for you?!
