### ISSUE TITLE
sts:GetFederationToken has no resource level permission

### ISSUE THREAD

**Issue by derBroBro** [widdix/complete-aws-iam-reference#3]
* Service: sts
* Action: GetFederationToken

I think the resource has no resouce level permission. arn:aws:sts::<id>:federated-user/<name> is just the output and can be used in other policies.

Details: http://docs.aws.amazon.com/STS/latest/APIReference/API_GetFederationToken.html?tag=vig-20

**Comment by michaelwittig** [comment]
Hi Malte! The documentation is very unclear here. The only thing I can find is this: http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_control-access_enable-create.html (last example)
But I don't know if this really works :)

**Comment by derBroBro** [comment]
Hi Micheal, you are totaly right, the documentation is very uncler. From my understanding, it allows to get the token with a subset of your (user) permission. So it makes only sense to limit the name or the permission. But this just my interpretatation. 
I think it makes sense to open a AWS ticket to clearify this.

**Comment by michaelwittig** [comment]
@derBroBro can you open the support ticket?

**Comment by derBroBro** [comment]
sure

**Comment by derBroBro** [comment]
Here is the feedback from the support. 
Resource specific conditions are not possible. The described resource can force the usage of a token name or prefix (arn:aws:sts::$account-id:federated-user/temp-*).

**Comment by michaelwittig** [comment]
thanks for researching this!
