### ISSUE TITLE
route53:ListResourceRecordSets

### ISSUE THREAD

**Issue by darkms** [widdix/complete-aws-iam-reference#5]
* Service: Amazon Route 53
* Action: route53:ListResourceRecordSets

Invalid "Supported Resource-Level Permissions" ('arn:aws:route53:::hostedzone/$hosted-zone-id/rrset'), it just doesn't work.
According to [AWS spec](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/r53-api-permissions-ref.html), only '*' is supported, which works.

**Comment by darkms** [comment]
There are also similar issues with actions:
route53:CreateHealthCheck (only * is allowed)
route53:DeleteHealthCheck (only * is allowed)
route53:ChangeResourceRecordSets (only 'arn:aws:route53:::hostedzone/${HostedZoneId}' is allowed - '/rrset' is not supported)

**Comment by michaelwittig** [comment]
thanks for reporting
