### ISSUE TITLE
cloudformation:ExecuteChangeSet

### ISSUE THREAD

**Issue by delphyne** [widdix/complete-aws-iam-reference#6]
Please make sure to provide all the fields and describe your issue.

* Service: cloudformation
* Action: ExecuteChangeSet

Please describe your issue here!

The documentation shows the following:

Supported Resource-Level Permissions
arn:aws:cloudformation:$region:$account-id:stack/$stack-name/*

however, the correct arn structure is:
arn:aws:cloudformation:$region:$account-id:changeSet/$change-set-name/$change-set-uuid

**Comment by michaelwittig** [comment]
Hi @delphyne can you point me to the documentation? I can't find it here: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-template.html

**Comment by delphyne** [comment]
I wasn't able to find official documentation on it.  I ended up having to create a changeSet to see its arn structure, then trial and error got me what i needed.

**Comment by michaelwittig** [comment]
I opened a support request to clarify this. maybe something is missing in the docs.

**Comment by michaelwittig** [comment]
The support proposed the following:

```
You can provide permission on a specific stack:
arn:aws:cloudformation:us-east-1:123456789012:stack/ustest/cc029ea0-1373-11e7-b677-5044763e8bb3
arn:aws:cloudformation:us-east-1:123456789012:stack/ustest/*

All Stacks:
arn:aws:cloudformation:us-east-1:123456789012:stack/*

I am not seeing a way to limit this to a specific region.
I also do not see a means of controlling access to a specific change set, the stack is the securable object in these cases.

With regards to conditions:
The IAM policy generator allows you to define values for the following Keys:
CloudFormation:TemplateURL
CloudFormation:StackPolicyURL
CloudFormation:ResourceTypes
CloudFormation:ChangeSetName
CloudFormation:RoleArn
```

**Comment by delphyne** [comment]
Interesting.  That definitely did not work for me.  I'll try it again the next time i need to write a policy for this, but for now, the policy i have is granting access.  thanks for looking into it.

**Comment by michaelwittig** [comment]
@delphyne I will close this for now. Feel free to reopen if you have new insights.
